# Goalkeepers

In [1]:
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import requests
from lxml import html
from bs4 import BeautifulSoup

In [2]:
pl = "https://fbref.com/en/comps/9/keepers/Premier-League-Stats"
liga = "https://fbref.com/en/comps/12/keepers/La-Liga-Stats"
seriea = "https://fbref.com/en/comps/11/keepers/Serie-A-Stats"
bundesliga = "https://fbref.com/en/comps/20/keepers/Bundesliga-Stats"
ligue1 = "https://fbref.com/en/comps/13/keepers/Ligue-1-Stats"

In [3]:
FBREFGK = pd.DataFrame(columns=['Player','Nation','Pos','Squad', 'Age', 'Born','MP' ,'Starts' 'Min', '90s'	'GA', 'GA90', 'SoTA', 'Saves', 'Save%' ,'W', 'D','L','CS','CS%','PKatt','PKA','PKsv', 'PKm','Save%'])

In [4]:
FBREFGK

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, Born, MP, StartsMin, 90sGA, GA90, SoTA, Saves, Save%, W, D, L, CS, CS%, PKatt, PKA, PKsv, PKm, Save%]
Index: []

[0 rows x 23 columns]

In [5]:
brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"

In [ ]:
def gkscraper (url):
    # First l'ets set up the web driver with the Brave browser
    options = Options()
    options.binary_location = brave_path
    driver = webdriver.Chrome(service=Service(), options=options)
    driver.get(url)

    # define a variable to hold the GKs table
    table = driver.find_element(By.XPATH , '//*[@id="stats_keeper"]/tbody')

    # Get all rows in the table
    rows = table.find_elements(By.TAG_NAME, 'tr')
    # Remove the header row
    rows.pop(25)
    # Loop through each row and extract the data
    for row in rows:
        # Get all cells in the row
        row_data = row.text.split(' ')
        row_data.pop(0)  # Remove the first element (the rank)
        row_data.remove('Matches')

        for i in range(len(row_data)):
            ind = row_data.index('GK')
            row_data.pop(ind-2)
            if ind > 2:
                name = row_data.pop(0)+ ' ' + row_data.pop(0)
            elif ind > 3:
                name = row_data.pop(0) + ' ' + row_data.pop(0) + ' ' + row_data.pop(0)
            row_data.insert(0, name)
            # Fixiing team names
            if len(row_data[ind) 
       
          
    # Close the driver after scraping
    driver.quit()
    return FBREFGK

gkscraper(pl)

['Alisson', 'br', 'BRA', 'GK', 'Liverpool', '31', '1992', '28', '28', '2,508', '27.9', '29', '1.04', '100', '73', '72.0', '18', '7', '3', '9', '32.1', '1', '1', '0', '0', '0.0']
26
['Alphonse', 'Areola', 'fr', 'FRA', 'GK', 'West', 'Ham', '31', '1993', '26', '25', '2,260', '25.1', '41', '1.63', '115', '77', '64.3', '5', '7', '13', '5', '20.0', '0', '0', '0', '0']
27
['Kepa', 'Arrizabalaga', 'es', 'ESP', 'GK', 'Bournemouth', '29', '1994', '31', '31', '2,790', '31.0', '39', '1.26', '134', '95', '73.9', '13', '7', '11', '8', '25.8', '4', '4', '0', '0', '0.0']
27
['Brandon', 'Austin', 'eng', 'ENG', 'GK', 'Tottenham', '25', '1999', '1', '1', '90', '1.0', '2', '2.00', '4', '2', '50.0', '0', '0', '1', '0', '0.0', '0', '0', '0', '0']
26
['Altay', 'Bayındır', 'tr', 'TUR', 'GK', 'Manchester', 'Utd', '26', '1998', '4', '4', '360', '4.0', '10', '2.50', '17', '8', '41.2', '1', '0', '3', '1', '25.0', '0', '0', '0', '0']
27
['Daniel', 'Bentley', 'eng', 'ENG', 'GK', 'Wolves', '31', '1993', '2', '2', '180', '2.0', '4', '2.00', '12', '8', '66.7', '1', '0', '1', '1', '50.0', '0', '0', '0', '0']
26
['Martin', 'Dúbravka', 'sk', 'SVK', 'GK', 'Newcastle', 'Utd', '35', '1989', '10', '10', '900', '10.0', '12', '1.20', '41', '29', '70.7', '7', '0', '3', '5', '50.0', '0', '0', '0', '0']
27
['Ederson', 'br', 'BRA', 'GK', 'Manchester', 'City', '30', '1993', '26', '26', '2,320', '25.8', '26', '1.01', '78', '53', '69.2', '16', '4', '6', '10', '38.5', '2', '2', '0', '0', '0.0']
27
['Łukasz', 'Fabiański', 'pl', 'POL', 'GK', 'West', 'Ham', '39', '1985', '14', '13', '1,160', '12.9', '21', '1.63', '71', '50', '74.6', '6', '3', '4', '2', '15.4', '3', '3', '0', '0', '0.0']
28
['Mark', 'Flekken', 'nl', 'NED', 'GK', 'Brentford', '31', '1993', '37', '37', '3,275', '36.4', '55', '1.51', '203', '150', '73.4', '16', '8', '13', '7', '18.9', '1', '1', '0', '0', '0.0']
27
['Fraser', 'Forster', 'eng', 'ENG', 'GK', 'Tottenham', '36', '1988', '7', '7', '630', '7.0', '15', '2.14', '42', '27', '69.0', '1', '2', '4', '1', '14.3', '2', '2', '0', '0', '0.0']
27
['Dean', 'Henderson', 'eng', 'ENG', 'GK', 'Crystal', 'Palace', '27', '1997', '38', '38', '3,420', '38.0', '51', '1.34', '150', '101', '66.7', '13', '14', '11', '11', '28.9', '2', '1', '1', '0', '50.0']
28
['Mads', 'Hermansen', 'dk', 'DEN', 'GK', 'Leicester', 'City', '24', '2000', '27', '27', '2,385', '26.5', '58', '2.19', '155', '99', '64.5', '3', '6', '18', '1', '3.7', '4', '3', '1', '0', '25.0']
28
['Vitezslav', 'Jaros', 'cz', 'CZE', 'GK', 'Liverpool', '23', '2001', '1', '0', '12', '0.1', '0', '0.00', '1', '1', '100.0', '0', '0', '0', '1', '0', '0', '0', '0']
25
['Sam', 'Johnstone', 'eng', 'ENG', 'GK', 'Wolves', '31', '1993', '7', '7', '630', '7.0', '17', '2.43', '39', '23', '61.5', '0', '1', '6', '0', '0.0', '2', '2', '0', '0', '0.0']
27
['Filip', 'Jørgensen', 'dk', 'DEN', 'GK', 'Chelsea', '22', '2002', '6', '6', '540', '6.0', '9', '1.50', '28', '19', '71.4', '3', '0', '3', '1', '16.7', '1', '1', '0', '0', '0.0']
27
['Caoimhín', 'Kelleher', 'ie', 'IRL', 'GK', 'Liverpool', '25', '1998', '10', '10', '900', '10.0', '12', '1.20', '37', '24', '67.6', '7', '2', '1', '4', '40.0', '1', '0', '1', '0', '100.0']
27
['Tom', 'King', 'wls', 'WAL', 'GK', 'Wolves', '29', '1995', '1', '0', '1', '0.0', '0', '0.00', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
24
['Antonín', 'Kinský', 'cz', 'CZE', 'GK', 'Tottenham', '21', '2003', '6', '6', '540', '6.0', '11', '1.83', '32', '23', '65.6', '1', '0', '5', '1', '16.7', '0', '0', '0', '0']
26
['Bernd', 'Leno', 'de', 'GER', 'GK', 'Fulham', '32', '1992', '38', '38', '3,420', '38.0', '54', '1.42', '159', '106', '67.9', '15', '9', '14', '5', '13.2', '4', '3', '1', '0', '25.0']
27
['Joe', 'Lumley', 'eng', 'ENG', 'GK', 'Southampton', '29', '1995', '3', '3', '270', '3.0', '7', '2.33', '20', '13', '65.0', '0', '1', '2', '0', '0.0', '0', '0', '0', '0']
26
['Emiliano', 'Martínez', 'ar', 'ARG', 'GK', 'Aston', 'Villa', '31', '1992', '37', '37', '3,194', '35.5', '45', '1.27', '142', '96', '69.0', '18', '9', '10', '8', '21.6', '2', '1', '1', '0', '50.0']
28
['Alex', 'McCarthy', 'eng', 'ENG', 'GK', 'Southampton', '34', '1989', '5', '5', '450', '5.0', '13', '2.60', '37', '24', '70.3', '0', '0', '5', '0', '0.0', '2', '2', '0', '0', '0.0']
27
['Arijanet', 'Muric', 'xk', 'KVX', 'GK', 'Ipswich', 'Town', '25', '1998', '18', '18', '1,620', '18.0', '33', '1.83', '100', '67', '70.0', '2', '6', '10', '1', '5.6', '3', '3', '0', '0', '0.0']
28
['Neto', 'br', 'BRA', 'GK', 'Bournemouth', '35', '1989', '2', '2', '180', '2.0', '2', '1.00', '13', '11', '84.6', '0', '2', '0', '0', '0.0', '0', '0', '0', '0']
25
['Robin', 'Olsen', 'se', 'SWE', 'GK', 'Aston', 'Villa', '34', '1990', '4', '1', '226', '2.5', '6', '2.39', '14', '8', '64.3', '1', '0', '0', '1', '100.0', '1', '1', '0', '0', '0.0']
28
['André', 'Onana', 'cm', 'CMR', 'GK', 'Manchester', 'Utd', '28', '1996', '34', '34', '3,060', '34.0', '44', '1.29', '132', '88', '68.9', '10', '9', '15', '9', '26.5', '4', '3', '1', '0', '25.0']
28
['Stefan', 'Ortega', 'de', 'GER', 'GK', 'Manchester', 'City', '31', '1992', '13', '12', '1,100', '12.2', '18', '1.47', '50', '33', '68.0', '5', '4', '3', '3', '25.0', '2', '2', '0', '0', '0.0']
28
['Alex', 'Palmer', 'eng', 'ENG', 'GK', 'Ipswich', 'Town', '27', '1996', '13', '13', '1,170', '13.0', '30', '2.31', '71', '43', '59.2', '1', '3', '9', '0', '0.0', '1', '1', '0', '0', '0.0']
28
['Jordan', 'Pickford', 'eng', 'ENG', 'GK', 'Everton', '30', '1994', '38', '38', '3,420', '38.0', '44', '1.16', '163', '117', '73.0', '11', '15', '12', '12', '31.6', '2', '0', '2', '0', '100.0']
27
['Nick', 'Pope', 'eng', 'ENG', 'GK', 'Newcastle', 'Utd', '32', '1992', '28', '28', '2,520', '28.0', '35', '1.25', '120', '86', '71.7', '13', '6', '9', '8', '28.6', '2', '1', '1', '0', '50.0']
28
['Hákon', 'Rafn', 'Valdimarsson', 'is', 'ISL', 'GK', 'Brentford', '22', '2001', '2', '1', '145', '1.6', '2', '1.24', '4', '3', '50.0', '0', '0', '1', '1', '100.0', '0', '0', '0', '0']
27
['Aaron', 'Ramsdale', 'eng', 'ENG', 'GK', 'Southampton', '26', '1998', '30', '30', '2,700', '30.0', '66', '2.20', '188', '120', '67.6', '2', '5', '23', '3', '10.0', '7', '5', '2', '0', '28.6']
27
['David', 'Raya', 'es', 'ESP', 'GK', 'Arsenal', '28', '1995', '38', '38', '3,420', '38.0', '34', '0.89', '120', '86', '74.2', '20', '14', '4', '13', '34.2', '3', '3', '0', '0', '0.0']
27
['José', 'Sá', 'pt', 'POR', 'GK', 'Wolves', '31', '1993', '29', '29', '2,609', '29.0', '48', '1.66', '117', '69', '63.2', '11', '5', '13', '7', '24.1', '7', '5', '2', '0', '28.6']
27
['Robert', 'Sánchez', 'es', 'ESP', 'GK', 'Chelsea', '26', '1997', '32', '32', '2,880', '32.0', '34', '1.06', '127', '92', '76.4', '17', '9', '6', '10', '31.3', '5', '4', '1', '0', '20.0']
27
['Matz', 'Sels', 'be', 'BEL', 'GK', "Nott'ham", 'Forest', '32', '1992', '38', '38', '3,420', '38.0', '46', '1.21', '165', '119', '73.9', '19', '8', '11', '13', '34.2', '3', '3', '0', '0', '0.0']
28
['Jason', 'Steele', 'eng', 'ENG', 'GK', 'Brighton', '33', '1990', '2', '2', '180', '2.0', '1', '0.50', '4', '3', '75.0', '2', '0', '0', '1', '50.0', '0', '0', '0', '0']
26
['Jakub', 'Stolarczyk', 'pl', 'POL', 'GK', 'Leicester', 'City', '23', '2000', '10', '10', '900', '10.0', '16', '1.60', '44', '28', '63.6', '3', '1', '6', '2', '20.0', '0', '0', '0', '0']
27
['Mark', 'Travers', 'ie', 'IRL', 'GK', 'Bournemouth', '25', '1999', '5', '5', '450', '5.0', '5', '1.00', '25', '20', '80.0', '2', '2', '1', '1', '20.0', '0', '0', '0', '0']
26
['Bart', 'Verbruggen', 'nl', 'NED', 'GK', 'Brighton', '21', '2002', '36', '36', '3,240', '36.0', '58', '1.61', '143', '87', '65.7', '14', '13', '9', '7', '19.4', '9', '9', '0', '0', '0.0']
27
['Guglielmo', 'Vicario', 'it', 'ITA', 'GK', 'Tottenham', '27', '1996', '24', '24', '2,160', '24.0', '37', '1.54', '102', '67', '64.7', '9', '3', '12', '4', '16.7', '1', '1', '0', '0', '0.0']
27
['Christian', 'Walton', 'eng', 'ENG', 'GK', 'Ipswich', 'Town', '28', '1995', '7', '7', '630', '7.0', '19', '2.71', '39', '20', '56.4', '1', '1', '5', '1', '14.3', '2', '2', '0', '0', '0.0']
28
['Danny', 'Ward', 'wls', 'WAL', 'GK', 'Leicester', 'City', '31', '1993', '2', '1', '135', '1.5', '6', '4.00', '10', '4', '40.0', '0', '0', '1', '0', '0.0', '0', '0', '0', '0']
27

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, Born, MP, StartsMin, 90sGA, GA90, SoTA, Saves, Save%, W, D, L, CS, CS%, PKatt, PKA, PKsv, PKm, Save%]
Index: []

[0 rows x 23 columns]

In [58]:
FBREFGK

Empty DataFrame
Columns: [Player, Nation, Pos, Squad, Age, Born, MP, StartsMin, 90sGA, GA90, SoTA, Saves, Save%, W, D, L, CS, CS%, PKatt, PKA, PKsv, PKm, Save%]
Index: []

[0 rows x 23 columns]