# Scraping TranfertMarket

## Prerequisites

### Import required Libraries

In [1]:
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import requests
from lxml import html

### Creating DataFrames

In [2]:
# crate empty DataFrames to store player data and contracts
PlayersTM = pd.DataFrame(columns=['Player', 'Value', 'Contract'])

## Scraping phase

### Setting up league URLs

In [3]:
# defining TOP5 Leagues url variable
PLurl = "https://www.transfermarkt.fr/premier-league/startseite/wettbewerb/GB1"
Ligaurl = "https://www.transfermarkt.fr/laliga/startseite/wettbewerb/ES1"
Bundesligaurl = "https://www.transfermarkt.fr/bundesliga/startseite/wettbewerb/L1"
SerieAurl = "https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1"
Ligue1url = "https://www.transfermarkt.fr/ligue-1/startseite/wettbewerb/FR1"

#defining path variable for the ChromeDriver
brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"

### Let's create a function to scrape team links from league pages

In [5]:
#create a function to colllecte teams website links

Links_list = []
def get_url(url):
    # Configure Brave path
 # UPDATE THIS

    # Set WebDriver options for Brave
    options = Options()
    options.binary_location = brave_path 
    # Initialize the driver (use ChromeDriver)
    driver = webdriver.Chrome(service=Service(), options=options)
    driver.get(url)

    # define a container to hold the teams table 
    container = driver.find_element(By.XPATH, '//*[@id="yw1"]/table/tbody')

    # search for team links within the container
    team_links = container.find_elements(By.TAG_NAME, 'a')
    team_urls = [link.get_attribute('href') for link in team_links]

    # adding the team URLs to the Links_list if they are not already present
    for link in team_urls:
        if link not in Links_list:
            Links_list.append(link)
    
    # close the driver
    driver.quit()
    return None

### Now let's apply our function to collect team links from the top 5 European leagues

In [6]:
get_url(PLurl)
get_url(Ligaurl)    
get_url(Bundesligaurl)
get_url(SerieAurl)
get_url(Ligue1url)

### Remove Duplicates

In [7]:
# we see that theres duplicates for all teams and some useless links (e.g. league links) so we will remove them
Links_list.pop(1)
Links_list.pop(41)
Links_list.pop(83)
Links_list.pop(118)
Links_list.pop(157)               
Links = []
# Remove duplicates
for i in range(len(Links_list)):
    if i % 2 == 0 and Links_list[i] not in Links:
        Links.append(Links_list[i])

### Check the number of teams

In [8]:
len(Links)

96

## Create a function that scrape individual players webpage

In [9]:
# Create a DataFrame to store each player name and their corresponding link
PLlinks = pd.DataFrame(columns = ['Player','link'])
# create lsit for scraped teams
scraped_Teams = []

In [10]:
not_scraped_Teams = []
def PlayerwebpagesFetcher(club_url):

    # First l'ets set up the web driver with the Brave browser
    options = Options()
    options.binary_location = brave_path
    driver = webdriver.Chrome(service=Service(), options=options)
    driver.get(club_url)

    # define a container to hold the players table
    container = driver.find_element(By.XPATH , "//*[@id='yw1']/table/tbody")
    # search for player links within the container
    alllinks= container.find_elements(By.XPATH , '//*[@id="yw1"]/table/tbody/tr/td/table/tbody/tr/td/a')

    try :
        # Extract player names and links
        for link in alllinks :
            link = link.get_attribute("href")
            name = " ".join(link[28:].split("/")[1].split("-"))

            # Check if the player is already in the DataFrame and skip if they are
            if name not in PLlinks['Player'].values :
                PLlinks.loc[len(PLlinks)] = [name,link]
            continue
    except  Exception as e:
        print(f"Theres an Error: {e} while scraping")

    
    driver.quit()
    return None

### Check the Function

In [11]:
club_url = "https://www.transfermarkt.fr/newcastle-united/startseite/verein/762/saison_id/2025"
PlayerwebpagesFetcher(club_url)

In [12]:
PLlinks.head()

                 Player                                               link
0             nick pope  https://www.transfermarkt.fr/nick-pope/profil/...
1  odysseas vlachodimos  https://www.transfermarkt.fr/odysseas-vlachodi...
2       martin dubravka  https://www.transfermarkt.fr/martin-dubravka/p...
3        mark gillespie  https://www.transfermarkt.fr/mark-gillespie/pr...
4           sven botman  https://www.transfermarkt.fr/sven-botman/profi...

In [20]:
# this bloc of code to scrape all players webpages links using the function we created above and skip teams that have already been scraped
for link in Links:
    try :
        if link not in scraped_Teams:
            PlayerwebpagesFetcher(link)
            scraped_Teams.append(link)
        continue
    except Exception as e:
        print(f"Theres an Error while scraping")
        not_scraped_Teams.append(link)
        continue

### Scraping function

In [14]:
# collect_player_data function to scrape player data (name, value) from each team page, and store it in the PlayersTM DataFrame
def collect_player_data(url):

    # Set up the headers to mimic a browser request
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    response = requests.get(url, headers=headers)
    tree = html.fromstring(response.content)

    # search for player features using XPath
    features = tree.xpath("//span[contains(@class, 'info-table__content info-table__content--bold')]/text()")
    name = features[0]
    Nvalue = tree.xpath("//a[contains(@href, '/marktwertverlauf/spieler/') and contains(@class , 'data-header__market-value-wrapper')]/text()")
    unit = tree.xpath("//span[@class = 'waehrung']/text()")

    # searching for the contract date inside a list "dates" that contains all dates (e.g. date when the player joined the club,...)
    dates = tree.xpath("//span[contains(text(), ', 20')]/text()")
    
    # We can choose the contract date based on the index of the dates list
    contract = dates[1]

    # Convert the value to a float based on the unit
    if unit[1] == 'm' :
        value = float(Nvalue[0]) * 1000000
    elif unit[1] == 'k' :
        value = float(Nvalue[0]) * 1000
    else :
        value = float(Nvalue[0])
    

    # insert the scraped data into the PlayersTM DataFrame
    PlayersTM.loc[len(PlayersTM)] = [name, value, contract]
    
    

    return None

### Lets test the function

In [15]:
# Example usage of the collect_player_data function
collect_player_data("https://www.transfermarkt.com/allen-obando/profil/spieler/1050373")

In [16]:
PlayersTM.head()

                      Player      Value      Contract
0  Allen Aldair Obando Ayoví  1500000.0  Dec 31, 2025

### see what we got

In [25]:
for link in PLlinks['link']:
    try :
        collect_player_data(link)
    except Exception as e:
        print(f"Error while scraping {link}: {e}")
        continue

Error while scraping https://www.transfermarkt.fr/nick-pope/profil/spieler/192080: list index out of range
Error while scraping https://www.transfermarkt.fr/odysseas-vlachodimos/profil/spieler/124419: list index out of range
Error while scraping https://www.transfermarkt.fr/martin-dubravka/profil/spieler/74960: list index out of range
Error while scraping https://www.transfermarkt.fr/mark-gillespie/profil/spieler/142389: list index out of range
Error while scraping https://www.transfermarkt.fr/sven-botman/profil/spieler/361093: list index out of range
Error while scraping https://www.transfermarkt.fr/fabian-schar/profil/spieler/135343: list index out of range
Error while scraping https://www.transfermarkt.fr/dan-burn/profil/spieler/134270: list index out of range
Error while scraping https://www.transfermarkt.fr/jamaal-lascelles/profil/spieler/183318: list index out of range
Error while scraping https://www.transfermarkt.fr/lewis-hall/profil/spieler/670858: list index out of range

KeyboardInterrupt:

### Final dataframes from TM

In [24]:
PlayersTM

                      Player      Value      Contract
0  Allen Aldair Obando Ayoví  1500000.0  Dec 31, 2025