# Scraping TranfertMarket

## Prerequisites

### Import required Libraries

In [28]:
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
import pandas as pd
import requests
import time
from requests.exceptions import HTTPError
from lxml import html

### creating DataFrames

In [2]:
# crate empty DataFrames to store player data and contracts
PlayersTM = pd.DataFrame(columns=['Player', 'Value'])
PlayersContracts = pd.DataFrame(columns=['Player', 'Contract'])

## Scraping phase

### Setting up league URLs

In [3]:
# defining TOP5 Leagues url variable
PLurl = "https://www.transfermarkt.fr/premier-league/startseite/wettbewerb/GB1"
Ligaurl = "https://www.transfermarkt.fr/laliga/startseite/wettbewerb/ES1"
Bundesligaurl = "https://www.transfermarkt.fr/bundesliga/startseite/wettbewerb/L1"
SerieAurl = "https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1"
Ligue1url = "https://www.transfermarkt.fr/ligue-1/startseite/wettbewerb/FR1"

#defining path variable for the ChromeDriver
path = "C:\\Users\\azedd\\Downloads\\chromedriver-win64\\chromedriver.exe"

### Let's create a function to scrape team links from league pages

In [4]:
#create a function to colllecte teams website links

Links_list = []
def get_url(url):
    # Configure Brave path
    brave_path = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"  # UPDATE THIS

    # Set WebDriver options for Brave
    options = Options()
    options.binary_location = brave_path 
    # Initialize the driver (use ChromeDriver)
    driver = webdriver.Chrome(service=Service(), options=options)
    driver.get(url)

    # define a container to hold the teams table 
    container = driver.find_element(By.XPATH, '//*[@id="yw1"]/table/tbody')

    # search for team links within the container
    team_links = container.find_elements(By.TAG_NAME, 'a')
    team_urls = [link.get_attribute('href') for link in team_links]

    # adding the team URLs to the Links_list if they are not already present
    for link in team_urls:
        if link not in Links_list:
            Links_list.append(link)
    
    # close the driver
    driver.quit()
    return None

### Now let's apply our function to collect team links from the top 5 European leagues

In [5]:
get_url(PLurl)
get_url(Ligaurl)    
get_url(Bundesligaurl)
get_url(SerieAurl)
get_url(Ligue1url)

### Remove Duplicates

In [6]:
# we see that theres duplicates for all teams and some useless links (e.g. league links) so we will remove them
Links_list.pop(1)
Links_list.pop(41)
Links_list.pop(83)
Links_list.pop(118)
Links_list.pop(157)               
Links = []
# Remove duplicates
for i in range(len(Links_list)):
    if i % 2 == 0 and Links_list[i] not in Links:
        Links.append(Links_list[i])

### Check the number of teams

In [7]:
len(Links)

96

## Create a function that scrape individual players webpage

In [29]:
all_players_webpages = []
scraped_teams = []

In [ ]:

def PlayerwebpagesFetcher(club_url, retries=3, delay=5):
    headers = {
        "User-Agent": "Mozilla/5.0"
    }
    for attempt in range(retries):
        try:
            response = requests.get(club_url, headers=headers)
            response.raise_for_status()
            tree = html.fromstring(response.content)
            player_links = tree.xpath("//a[contains(@href, '/profil/spieler/')]/@href")
            for href in set(player_links):
                if href.startswith("/"):
                    full_url = "https://www.transfermarkt.com" + href
                else:
                    full_url = href
                all_players_webpages.append(full_url)
            scraped_teams.append(club_url)
            return f"links of players in team No : {Links.index(club_url)} successfully fetched"
        except HTTPError as e:
            print(f"HTTPError: {e}. Retrying in {delay} seconds...")
            time.sleep(delay)
    print(f"Failed to fetch {club_url} after {retries} attempts.")
    return []

### Check the Function

In [31]:
club_url = "https://www.transfermarkt.fr/newcastle-united/startseite/verein/762/saison_id/2025"
player_urls = PlayerwebpagesFetcher(club_url)
print(player_urls)

links of players in team No : 7 successfully fetched

In [ ]:
for link in Links :
    if link not in scraped_teams :
        PlayerwebpagesFetcher(link)
        scraped_teams.append(link)
    continue

HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/nottingham-forest/startseite/verein/703/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/nottingham-forest/startseite/verein/703/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/crystal-palace/startseite/verein/873/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/crystal-palace/startseite/verein/873/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-brentford/startseite/verein/1148/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-bournemouth/startseite/verein/989/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-bournemouth/startseite/verein/989/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-bournemouth/startseite/verein/989/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/afc-bournemouth/startseite/verein/989/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/west-ham-united/startseite/verein/379/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/wolverhampton-wanderers/startseite/verein/543/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/wolverhampton-wanderers/startseite/verein/543/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/wolverhampton-wanderers/startseite/verein/543/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/wolverhampton-wanderers/startseite/verein/543/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-burnley/startseite/verein/1132/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-sunderland/startseite/verein/289/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-sunderland/startseite/verein/289/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/afc-sunderland/startseite/verein/289/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/afc-sunderland/startseite/verein/289/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-madrid/startseite/verein/418/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-barcelona/startseite/verein/131/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-barcelona/startseite/verein/131/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-barcelona/startseite/verein/131/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/fc-barcelona/startseite/verein/131/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/atletico-madrid/startseite/verein/13/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/atletico-madrid/startseite/verein/13/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/athletic-bilbao/startseite/verein/621/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/athletic-bilbao/startseite/verein/621/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-betis-sevilla/startseite/verein/150/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-betis-sevilla/startseite/verein/150/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-betis-sevilla/startseite/verein/150/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/real-betis-sevilla/startseite/verein/150/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-sevilla/startseite/verein/368/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-girona/startseite/verein/12321/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ca-osasuna/startseite/verein/331/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ca-osasuna/startseite/verein/331/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ca-osasuna/startseite/verein/331/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/ca-osasuna/startseite/verein/331/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-getafe/startseite/verein/3709/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-getafe/startseite/verein/3709/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-getafe/startseite/verein/3709/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/fc-getafe/startseite/verein/3709/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/rcd-mallorca/startseite/verein/237/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/rayo-vallecano/startseite/verein/367/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/deportivo-alaves/startseite/verein/1108/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/deportivo-alaves/startseite/verein/1108/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/deportivo-alaves/startseite/verein/1108/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/deportivo-alaves/startseite/verein/1108/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ud-levante/startseite/verein/3368/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-oviedo/startseite/verein/2497/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-oviedo/startseite/verein/2497/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/real-oviedo/startseite/verein/2497/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/real-oviedo/startseite/verein/2497/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-bayern-munchen/startseite/verein/27/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-bayern-munchen/startseite/verein/27/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/bayer-04-leverkusen/startseite/verein/15/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/vfb-stuttgart/startseite/verein/79/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/vfb-stuttgart/startseite/verein/79/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/vfb-stuttgart/startseite/verein/79/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/vfb-stuttgart/startseite/verein/79/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/vfl-wolfsburg/startseite/verein/82/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sc-freiburg/startseite/verein/60/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sc-freiburg/startseite/verein/60/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sc-freiburg/startseite/verein/60/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/sc-freiburg/startseite/verein/60/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/borussia-monchengladbach/startseite/verein/18/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/borussia-monchengladbach/startseite/verein/18/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/borussia-monchengladbach/startseite/verein/18/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/borussia-monchengladbach/startseite/verein/18/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/1-fsv-mainz-05/startseite/verein/39/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/1-fsv-mainz-05/startseite/verein/39/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/1-fsv-mainz-05/startseite/verein/39/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/1-fsv-mainz-05/startseite/verein/39/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sv-werder-bremen/startseite/verein/86/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sv-werder-bremen/startseite/verein/86/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/sv-werder-bremen/startseite/verein/86/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/sv-werder-bremen/startseite/verein/86/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/hamburger-sv/startseite/verein/41/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/hamburger-sv/startseite/verein/41/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/hamburger-sv/startseite/verein/41/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/hamburger-sv/startseite/verein/41/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/1-fc-heidenheim-1846/startseite/verein/2036/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-st-pauli/startseite/verein/35/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/inter-mailand/startseite/verein/46/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/juventus-turin/kader/verein/506/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/juventus-turin/kader/verein/506/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/serie-a/startseite/wettbewerb/IT1. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/atalanta-bergamo/startseite/verein/800/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/atalanta-bergamo/startseite/verein/800/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/atalanta-bergamo/startseite/verein/800/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/atalanta-bergamo/startseite/verein/800/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-mailand/startseite/verein/5/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-mailand/startseite/verein/5/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-mailand/startseite/verein/5/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/ac-mailand/startseite/verein/5/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-bologna/startseite/verein/1025/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-bologna/startseite/verein/1025/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-bologna/startseite/verein/1025/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/fc-bologna/startseite/verein/1025/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-florenz/startseite/verein/430/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-florenz/startseite/verein/430/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/ac-florenz/startseite/verein/430/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/ac-florenz/startseite/verein/430/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/lazio-rom/startseite/verein/398/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/udinese-calcio/startseite/verein/410/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/udinese-calcio/startseite/verein/410/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/udinese-calcio/startseite/verein/410/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/udinese-calcio/startseite/verein/410/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-turin/startseite/verein/416/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-turin/startseite/verein/416/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/fc-turin/startseite/verein/416/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/fc-turin/startseite/verein/416/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/genua-cfc/startseite/verein/252/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/genua-cfc/startseite/verein/252/saison_id/2025. Retrying in 5 seconds...
HTTPError: 408 Client Error: Request Time-out for url: https://www.transfermarkt.fr/us-sassuolo/startseite/verein/6574/saison_id/2025. Retrying in 5 seconds...
HTTPError: 502 Server Error: Bad Gateway for url: https://www.transfermarkt.fr/us-lecce/startseite/verein/1005/saison_id/2025. Retrying in 5 seconds...
HTTPError: 502 Server Error: Bad Gateway for url: https://www.transfermarkt.fr/us-lecce/startseite/verein/1005/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/us-lecce/startseite/verein/1005/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/us-lecce/startseite/verein/1005/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/hellas-verona/startseite/verein/276/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/us-cremonese/startseite/verein/2239/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/as-monaco/startseite/verein/162/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/as-monaco/startseite/verein/162/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/as-monaco/startseite/verein/162/saison_id/2025. Retrying in 5 seconds...
Failed to fetch https://www.transfermarkt.fr/as-monaco/startseite/verein/162/saison_id/2025 after 3 attempts.
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/losc-lille/startseite/verein/1082/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/losc-lille/startseite/verein/1082/saison_id/2025. Retrying in 5 seconds...
HTTPError: 503 Server Error: Service Unavailable for url: https://www.transfermarkt.fr/losc-lille/startseite/verein/1082/saison_id/2025. Retrying in 5 seconds...

### Scraping function

In [20]:
# collect_player_data function to scrape player data (e.g. name, age,...) from each team page, and store it in the PlayersTM DataFrame
def collect_player_data(url):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    response = requests.get(url, headers=headers)
    tree = html.fromstring(response.content)
    # Get all player rows
    rows = tree.xpath('//table[@class="items"]/tbody/tr[contains(@class, "odd") or contains(@class, "even")]')

    for row in rows:
        # Name
        name_list = row.xpath('.//td[contains(@class, "hauptlink")]/a/text()')
        if not name_list:
            continue
        name = name_list[0].strip()

        # Value
        value = row.xpath('normalize-space(.//td[contains(@class, "rechts") and contains(@class, "hauptlink")])')

        # Check if player already exists in PlayersTM DataFrame
        if name in PlayersTM['Player'].values:
            continue

        # Append data to PlayersTM DataFrame
        PlayersTM.loc[len(PlayersTM)] = [name, value]
    return None

### Lets test the function

In [21]:

collect_player_data("https://www.transfermarkt.fr/montpellier-hsc/startseite/verein/969/saison_id/2024")

In [23]:
PlayersTM
all_players_webpages

['https://www.transfermarkt.com/alex-murphy/profil/spieler/900601',
 'https://www.transfermarkt.com/martin-dubravka/profil/spieler/74960',
 'https://www.transfermarkt.com/anthony-gordon/profil/spieler/503733',
 'https://www.transfermarkt.com/isaac-hayden/profil/spieler/206225',
 'https://www.transfermarkt.com/joelinton/profil/spieler/333241',
 'https://www.transfermarkt.com/emil-krafth/profil/spieler/184528',
 'https://www.transfermarkt.com/harvey-barnes/profil/spieler/398065',
 'https://www.transfermarkt.com/jamal-lewis/profil/spieler/346018',
 'https://www.transfermarkt.com/alexander-isak/profil/spieler/349066',
 'https://www.transfermarkt.com/william-osula/profil/spieler/609556',
 'https://www.transfermarkt.com/matt-targett/profil/spieler/250478',
 'https://www.transfermarkt.com/sean-longstaff/profil/spieler/346707',
 'https://www.transfermarkt.com/mark-gillespie/profil/spieler/142389',
 'https://www.transfermarkt.com/dan-burn/profil/spieler/134270',
 'https://www.transfermarkt.com/bruno-guimaraes/profil/spieler/520624',
 'https://www.transfermarkt.com/harrison-ashby/profil/spieler/559130',
 'https://www.transfermarkt.com/lewis-miley/profil/spieler/922769',
 'https://www.transfermarkt.com/lloyd-kelly/profil/spieler/480116',
 'https://www.transfermarkt.com/jamaal-lascelles/profil/spieler/183318',
 'https://www.transfermarkt.com/joe-willock/profil/spieler/340329',
 'https://www.transfermarkt.com/john-ruddy/profil/spieler/29712',
 'https://www.transfermarkt.com/kieran-trippier/profil/spieler/95810',
 'https://www.transfermarkt.com/odysseas-vlachodimos/profil/spieler/124419',
 'https://www.transfermarkt.com/sandro-tonali/profil/spieler/397033',
 'https://www.transfermarkt.com/joe-white/profil/spieler/614811',
 'https://www.transfermarkt.com/sven-botman/profil/spieler/361093',
 'https://www.transfermarkt.com/fabian-schar/profil/spieler/135343',
 'https://www.transfermarkt.com/callum-wilson/profil/spieler/123682',
 'https://www.transfermarkt.com/tino-livramento/profil/spieler/503981',
 'https://www.transfermarkt.com/lewis-hall/profil/spieler/670858',
 'https://www.transfermarkt.com/jacob-murphy/profil/spieler/199527',
 'https://www.transfermarkt.com/antonito-cordero/profil/spieler/1178393',
 'https://www.transfermarkt.com/nick-pope/profil/spieler/192080',
 'https://www.transfermarkt.com/alex-murphy/profil/spieler/900601',
 'https://www.transfermarkt.com/martin-dubravka/profil/spieler/74960',
 'https://www.transfermarkt.com/anthony-gordon/profil/spieler/503733',
 'https://www.transfermarkt.com/isaac-hayden/profil/spieler/206225',
 'https://www.transfermarkt.com/joelinton/profil/spieler/333241',
 'https://www.transfermarkt.com/emil-krafth/profil/spieler/184528',
 'https://www.transfermarkt.com/harvey-barnes/profil/spieler/398065',
 'https://www.transfermarkt.com/jamal-lewis/profil/spieler/346018',
 'https://www.transfermarkt.com/alexander-isak/profil/spieler/349066',
 'https://www.transfermarkt.com/william-osula/profil/spieler/609556',
 'https://www.transfermarkt.com/matt-targett/profil/spieler/250478',
 'https://www.transfermarkt.com/sean-longstaff/profil/spieler/346707',
 'https://www.transfermarkt.com/mark-gillespie/profil/spieler/142389',
 'https://www.transfermarkt.com/dan-burn/profil/spieler/134270',
 'https://www.transfermarkt.com/bruno-guimaraes/profil/spieler/520624',
 'https://www.transfermarkt.com/harrison-ashby/profil/spieler/559130',
 'https://www.transfermarkt.com/lewis-miley/profil/spieler/922769',
 'https://www.transfermarkt.com/lloyd-kelly/profil/spieler/480116',
 'https://www.transfermarkt.com/jamaal-lascelles/profil/spieler/183318',
 'https://www.transfermarkt.com/joe-willock/profil/spieler/340329',
 'https://www.transfermarkt.com/john-ruddy/profil/spieler/29712',
 'https://www.transfermarkt.com/kieran-trippier/profil/spieler/95810',
 'https://www.transfermarkt.com/odysseas-vlachodimos/profil/spieler/124419',
 'https://www.transfermarkt.com/sandro-tonali/profil/spieler/397033',
 'https://www.transfermarkt.com/joe-white/profil/spieler/614811',
 'https://www.transfermarkt.com/sven-botman/profil/spieler/361093',
 'https://www.transfermarkt.com/fabian-schar/profil/spieler/135343',
 'https://www.transfermarkt.com/callum-wilson/profil/spieler/123682',
 'https://www.transfermarkt.com/tino-livramento/profil/spieler/503981',
 'https://www.transfermarkt.com/lewis-hall/profil/spieler/670858',
 'https://www.transfermarkt.com/jacob-murphy/profil/spieler/199527',
 'https://www.transfermarkt.com/antonito-cordero/profil/spieler/1178393',
 'https://www.transfermarkt.com/nick-pope/profil/spieler/192080',
 'https://www.transfermarkt.com/matheus-nunes/profil/spieler/601883',
 'https://www.transfermarkt.com/john-stones/profil/spieler/186590',
 'https://www.transfermarkt.com/vitor-reis/profil/spieler/1005575',
 'https://www.transfermarkt.com/james-mcatee/profil/spieler/583199',
 'https://www.transfermarkt.com/josko-gvardiol/profil/spieler/475959',
 'https://www.transfermarkt.com/savinho/profil/spieler/743591',
 'https://www.transfermarkt.com/nico-oreilly/profil/spieler/743413',
 'https://www.transfermarkt.com/jack-grealish/profil/spieler/203460',
 'https://www.transfermarkt.com/rayan-cherki/profil/spieler/607223',
 'https://www.transfermarkt.com/issa-kabore/profil/spieler/649452',
 'https://www.transfermarkt.com/phil-foden/profil/spieler/406635',
 'https://www.transfermarkt.com/erling-haaland/profil/spieler/418560',
 'https://www.transfermarkt.com/oscar-bobb/profil/spieler/661207',
 'https://www.transfermarkt.com/rayan-ait-nouri/profil/spieler/578391',
 'https://www.transfermarkt.com/omar-marmoush/profil/spieler/445939',
 'https://www.transfermarkt.com/scott-carson/profil/spieler/14555',
 'https://www.transfermarkt.com/bernardo-silva/profil/spieler/241641',
 'https://www.transfermarkt.com/tijjani-reijnders/profil/spieler/460939',
 'https://www.transfermarkt.com/maximo-perrone/profil/spieler/668547',
 'https://www.transfermarkt.com/josh-wilson-esbrand/profil/spieler/576121',
 'https://www.transfermarkt.com/marcus-bettinelli/profil/spieler/116648',
 'https://www.transfermarkt.com/jeremy-doku/profil/spieler/486049',
 'https://www.transfermarkt.com/rico-lewis/profil/spieler/701057',
 'https://www.transfermarkt.com/rodri/profil/spieler/357565',
 'https://www.transfermarkt.com/mateo-kovacic/profil/spieler/51471',
 'https://www.transfermarkt.com/manuel-akanji/profil/spieler/284730',
 'https://www.transfermarkt.com/juma-bah/profil/spieler/1121298',
 'https://www.transfermarkt.com/nathan-ake/profil/spieler/177476',
 'https://www.transfermarkt.com/kevin-de-bruyne/profil/spieler/88755',
 'https://www.transfermarkt.com/abdukodir-khusanov/profil/spieler/763079',
 'https://www.transfermarkt.com/stefan-ortega/profil/spieler/85941',
 'https://www.transfermarkt.com/yan-couto/profil/spieler/627228',
 'https://www.transfermarkt.com/kalvin-phillips/profil/spieler/351749',
 'https://www.transfermarkt.com/kyle-walker/profil/spieler/95424',
 'https://www.transfermarkt.com/claudio-echeverri/profil/spieler/994536',
 'https://www.transfermarkt.com/ilkay-gundogan/profil/spieler/53622',
 'https://www.transfermarkt.com/nico-gonzalez/profil/spieler/466805',
 'https://www.transfermarkt.com/ederson/profil/spieler/238223',
 'https://www.transfermarkt.com/ruben-dias/profil/spieler/258004',
 'https://www.transfermarkt.com/erling-haaland/profil/spieler/418560',
 'https://www.transfermarkt.com/christian-norgaard/profil/spieler/148367',
 'https://www.transfermarkt.com/jakub-kiwior/profil/spieler/425918',
 'https://www.transfermarkt.com/thomas-partey/profil/spieler/230784',
 'https://www.transfermarkt.com/mikel-merino/profil/spieler/338424',
 'https://www.transfermarkt.com/reiss-nelson/profil/spieler/340325',
 'https://www.transfermarkt.com/myles-lewis-skelly/profil/spieler/890721',
 'https://www.transfermarkt.com/jorginho/profil/spieler/102017',
 'https://www.transfermarkt.com/william-saliba/profil/spieler/495666',
 'https://www.transfermarkt.com/leandro-trossard/profil/spieler/144028',
 'https://www.transfermarkt.com/martin-zubimendi/profil/spieler/423440',
 'https://www.transfermarkt.com/jurrien-timber/profil/spieler/420243',
 'https://www.transfermarkt.com/christian-norgaard/profil/spieler/148367',
 'https://www.transfermarkt.com/kieran-tierney/profil/spieler/300716',
 'https://www.transfermarkt.com/ethan-nwaneri/profil/spieler/890719',
 'https://www.transfermarkt.com/kepa-arrizabalaga/profil/spieler/192279',
 'https://www.transfermarkt.com/kai-havertz/profil/spieler/309400',
 'https://www.transfermarkt.com/oleksandr-zinchenko/profil/spieler/203853',
 'https://www.transfermarkt.com/albert-sambi-lokonga/profil/spieler/381967',
 'https://www.transfermarkt.com/takehiro-tomiyasu/profil/spieler/331560',
 'https://www.transfermarkt.com/riccardo-calafiori/profil/spieler/502821',
 'https://www.transfermarkt.com/fabio-vieira/profil/spieler/537598',
 'https://www.transfermarkt.com/gabriel-jesus/profil/spieler/363205',
 'https://www.transfermarkt.com/gabriel-magalhaes/profil/spieler/435338',
 'https://www.transfermarkt.com/declan-rice/profil/spieler/357662',
 'https://www.transfermarkt.com/ben-white/profil/spieler/335721',
 'https://www.transfermarkt.com/david-raya/profil/spieler/262749',
 'https://www.transfermarkt.com/bukayo-saka/profil/spieler/433177',
 'https://www.transfermarkt.com/gabriel-martinelli/profil/spieler/655488',
 'https://www.transfermarkt.com/karl-hein/profil/spieler/493513',
 'https://www.transfermarkt.com/nuno-tavares/profil/spieler/535955',
 'https://www.transfermarkt.com/martin-odegaard/profil/spieler/316264',
 'https://www.transfermarkt.com/andrew-robertson/profil/spieler/234803',
 'https://www.transfermarkt.com/giorgi-mamardashvili/profil/spieler/502676',
 'https://www.transfermarkt.com/konstantinos-tsimikas/profil/spieler/338070',
 'https://www.transfermarkt.com/ryan-gravenberch/profil/spieler/478573',
 'https://www.transfermarkt.com/harvey-elliott/profil/spieler/565822',
 'https://www.transfermarkt.com/federico-chiesa/profil/spieler/341092',
 'https://www.transfermarkt.com/cody-gakpo/profil/spieler/434675',
 'https://www.transfermarkt.com/trent-alexander-arnold/profil/spieler/314353',
 'https://www.transfermarkt.com/conor-bradley/profil/spieler/624258',
 'https://www.transfermarkt.com/alisson/profil/spieler/105470',
 'https://www.transfermarkt.com/virgil-van-dijk/profil/spieler/139208',
 'https://www.transfermarkt.com/mohamed-salah/profil/spieler/148455',
 'https://www.transfermarkt.com/joe-gomez/profil/spieler/256178',
 'https://www.transfermarkt.com/wataru-endo/profil/spieler/146310',
 'https://www.transfermarkt.com/florian-wirtz/profil/spieler/598577',
 'https://www.transfermarkt.com/rhys-williams/profil/spieler/503679',
 'https://www.transfermarkt.com/ben-doak/profil/spieler/719673',
 'https://www.transfermarkt.com/calvin-ramsay/profil/spieler/633652',
 'https://www.transfermarkt.com/luis-diaz/profil/spieler/480692',
 'https://www.transfermarkt.com/armin-pecsi/profil/spieler/933215',
 'https://www.transfermarkt.com/tyler-morton/profil/spieler/618494',
 'https://www.transfermarkt.com/vitezslav-jaros/profil/spieler/486604',
 'https://www.transfermarkt.com/ibrahima-konate/profil/spieler/357119',
 'https://www.transfermarkt.com/caoimhin-kelleher/profil/spieler/340918',
 'https://www.transfermarkt.com/milos-kerkez/profil/spieler/730861',
 'https://www.transfermarkt.com/darwin-nunez/profil/spieler/546543',
 'https://www.transfermarkt.com/jeremie-frimpong/profil/spieler/484547',
 'https://www.transfermarkt.com/jarell-quansah/profil/spieler/632349',
 'https://www.transfermarkt.com/curtis-jones/profil/spieler/433188',
 'https://www.transfermarkt.com/dominik-szoboszlai/profil/spieler/451276',
 'https://www.transfermarkt.com/nat-phillips/profil/spieler/371814',
 'https://www.transfermarkt.com/alexis-mac-allister/profil/spieler/534033',
 'https://www.transfermarkt.com/freddie-woodman/profil/spieler/226049',
 'https://www.transfermarkt.com/stefan-bajcetic/profil/spieler/864799',
 'https://www.transfermarkt.com/james-maddison/profil/spieler/294057',
 'https://www.transfermarkt.com/alfie-whiteman/profil/spieler/282823',
 'https://www.transfermarkt.com/dominic-solanke/profil/spieler/258889',
 'https://www.transfermarkt.com/lucas-bergvall/profil/spieler/866246',
 'https://www.transfermarkt.com/mathys-tel/profil/spieler/801734',
 'https://www.transfermarkt.com/antonin-kinsky/profil/spieler/725912',
 'https://www.transfermarkt.com/mohammed-kudus/profil/spieler/543499',
 'https://www.transfermarkt.com/pape-matar-sarr/profil/spieler/568693',
 'https://www.transfermarkt.com/luka-vuskovic/profil/spieler/892160',
 'https://www.transfermarkt.com/archie-gray/profil/spieler/922693',
 'https://www.transfermarkt.com/dejan-kulusevski/profil/spieler/431755',
 'https://www.transfermarkt.com/dane-scarlett/profil/spieler/670883',
 'https://www.transfermarkt.com/richarlison/profil/spieler/378710',
 'https://www.transfermarkt.com/radu-dragusin/profil/spieler/568559',
 'https://www.transfermarkt.com/guglielmo-vicario/profil/spieler/286047',
 'https://www.transfermarkt.com/ashley-phillips/profil/spieler/859951',
 'https://www.transfermarkt.com/yves-bissouma/profil/spieler/410425',
 'https://www.transfermarkt.com/heung-min-son/profil/spieler/91845',
 'https://www.transfermarkt.com/manor-solomon/profil/spieler/396638',
 'https://www.transfermarkt.com/bryan-gil/profil/spieler/537382',
 'https://www.transfermarkt.com/djed-spence/profil/spieler/483348',
 'https://www.transfermarkt.com/pierre-emile-hojbjerg/profil/spieler/167799',
 'https://www.transfermarkt.com/min-hyeok-yang/profil/spieler/1004327',
 'https://www.transfermarkt.com/rodrigo-bentancur/profil/spieler/354362',
 'https://www.transfermarkt.com/kota-takai/profil/spieler/671108',
 'https://www.transfermarkt.com/brennan-johnson/profil/spieler/470607',
 'https://www.transfermarkt.com/brandon-austin/profil/spieler/428016',
 'https://www.transfermarkt.com/alfie-devine/profil/spieler/728734',
 'https://www.transfermarkt.com/micky-van-de-ven/profil/spieler/557459',
 'https://www.transfermarkt.com/mikey-moore/profil/spieler/1011147',
 'https://www.transfermarkt.com/destiny-udogie/profil/spieler/556385',
 'https://www.transfermarkt.com/kevin-danso/profil/spieler/263236',
 'https://www.transfermarkt.com/alejo-veliz/profil/spieler/888493',
 'https://www.transfermarkt.com/ben-davies/profil/spieler/192765',
 'https://www.transfermarkt.com/cristian-romero/profil/spieler/355915',
 'https://www.transfermarkt.com/pedro-porro/profil/spieler/553875',
 'https://www.transfermarkt.com/wilson-odobert/profil/spieler/743498',
 'https://www.transfermarkt.com/sergio-reguilon/profil/spieler/282429',
 'https://www.transfermarkt.com/fraser-forster/profil/spieler/52570',
 'https://www.transfermarkt.com/alejandro-garnacho/profil/spieler/811779',
 'https://www.transfermarkt.com/matthijs-de-ligt/profil/spieler/326031',
 'https://www.transfermarkt.com/luke-shaw/profil/spieler/183288',
 'https://www.transfermarkt.com/kobbie-mainoo/profil/spieler/820374',
 'https://www.transfermarkt.com/matheus-cunha/profil/spieler/517894',
 'https://www.transfermarkt.com/tyler-fredricson/profil/spieler/911424',
 'https://www.transfermarkt.com/chido-obi/profil/spieler/1042886',
 'https://www.transfermarkt.com/diogo-dalot/profil/spieler/357147',
 'https://www.transfermarkt.com/diego-leon/profil/spieler/1283997',
 'https://www.transfermarkt.com/ethan-wheatley/profil/spieler/888639',
 'https://www.transfermarkt.com/victor-lindelof/profil/spieler/184573',
 'https://www.transfermarkt.com/toby-collyer/profil/spieler/654253',
 'https://www.transfermarkt.com/patrick-dorgu/profil/spieler/926952',
 'https://www.transfermarkt.com/joshua-zirkzee/profil/spieler/435648',
 'https://www.transfermarkt.com/ayden-heaven/profil/spieler/1078163',
 'https://www.transfermarkt.com/christian-eriksen/profil/spieler/69633',
 'https://www.transfermarkt.com/altay-bayindir/profil/spieler/336077',
 'https://www.transfermarkt.com/mason-mount/profil/spieler/346483',
 'https://www.transfermarkt.com/manuel-ugarte/profil/spieler/476701',
 'https://www.transfermarkt.com/noussair-mazraoui/profil/spieler/340456',
 'https://www.transfermarkt.com/jonny-evans/profil/spieler/42412',
 'https://www.transfermarkt.com/casemiro/profil/spieler/16306',
 'https://www.transfermarkt.com/antony/profil/spieler/602105',
 'https://www.transfermarkt.com/leny-yoro/profil/spieler/923831',
 'https://www.transfermarkt.com/harry-amass/profil/spieler/1011738',
 'https://www.transfermarkt.com/enzo-kana-biyik/profil/spieler/1194813',
 'https://www.transfermarkt.com/tom-heaton/profil/spieler/34130',
 'https://www.transfermarkt.com/lisandro-martinez/profil/spieler/480762',
 'https://www.transfermarkt.com/rasmus-hojlund/profil/spieler/610442',
 'https://www.transfermarkt.com/jadon-sancho/profil/spieler/401173',
 'https://www.transfermarkt.com/amad-diallo/profil/spieler/536835',
 'https://www.transfermarkt.com/tyrell-malacia/profil/spieler/339340',
 'https://www.transfermarkt.com/bruno-fernandes/profil/spieler/240306',
 'https://www.transfermarkt.com/marcus-rashford/profil/spieler/258923',
 'https://www.transfermarkt.com/andre-onana/profil/spieler/234509',
 'https://www.transfermarkt.com/harry-maguire/profil/spieler/177907',
 'https://www.transfermarkt.com/daniel-gore/profil/spieler/747153',
 'https://www.transfermarkt.com/olivier-boscagli/profil/spieler/318508',
 'https://www.transfermarkt.com/maxim-de-cuyper/profil/spieler/429915',
 'https://www.transfermarkt.com/carlos-baleba/profil/spieler/973085',
 'https://www.transfermarkt.com/jason-steele/profil/spieler/73564',
 'https://www.transfermarkt.com/kaoru-mitoma/profil/spieler/504849',
 'https://www.transfermarkt.com/diego-coppola/profil/spieler/660860',
 'https://www.transfermarkt.com/julio-enciso/profil/spieler/660867',
 'https://www.transfermarkt.com/mats-wieffer/profil/spieler/415381',
 'https://www.transfermarkt.com/simon-adingra/profil/spieler/658536',
 'https://www.transfermarkt.com/danny-welbeck/profil/spieler/67063',
 'https://www.transfermarkt.com/abdallah-sima/profil/spieler/776798',
 'https://www.transfermarkt.com/yasin-ayari/profil/spieler/667287',
 'https://www.transfermarkt.com/malick-yalcouye/profil/spieler/1178758',
 'https://www.transfermarkt.com/charalampos-kostoulas/profil/spieler/1060087',
 'https://www.transfermarkt.com/igor/profil/spieler/380350',
 'https://www.transfermarkt.com/kjell-scherpen/profil/spieler/463527',
 'https://www.transfermarkt.com/eiran-cashin/profil/spieler/581330',
 'https://www.transfermarkt.com/georginio-rutter/profil/spieler/538977',
 'https://www.transfermarkt.com/bart-verbruggen/profil/spieler/565093',
 'https://www.transfermarkt.com/joao-pedro/profil/spieler/626724',
 'https://www.transfermarkt.com/do-young-yoon/profil/spieler/1015959',
 'https://www.transfermarkt.com/jeremy-sarmiento/profil/spieler/568005',
 'https://www.transfermarkt.com/ibrahim-osman/profil/spieler/1110406',
 'https://www.transfermarkt.com/evan-ferguson/profil/spieler/648046',
 'https://www.transfermarkt.com/solly-march/profil/spieler/209212',
 'https://www.transfermarkt.com/andrew-moran/profil/spieler/724537',
 'https://www.transfermarkt.com/diego-gomez/profil/spieler/996897',
 'https://www.transfermarkt.com/jack-hinshelwood/profil/spieler/867688',
 'https://www.transfermarkt.com/jan-paul-van-hecke/profil/spieler/576314',
 'https://www.transfermarkt.com/james-milner/profil/spieler/3333',
 'https://www.transfermarkt.com/yankuba-minteh/profil/spieler/1012534',
 'https://www.transfermarkt.com/valentin-barco/profil/spieler/849410',
 'https://www.transfermarkt.com/brajan-gruda/profil/spieler/700106',
 'https://www.transfermarkt.com/tariq-lamptey/profil/spieler/504148',
 'https://www.transfermarkt.com/tom-watson/profil/spieler/933018',
 'https://www.transfermarkt.com/matt-oriley/profil/spieler/406634',
 'https://www.transfermarkt.com/adam-webster/profil/spieler/212847',
 'https://www.transfermarkt.com/lewis-dunk/profil/spieler/148153',

### see what we got

In [24]:
PlayersTM

                   Player        Value
0        Benjamin Lecomte  1,50 mio. €
1         Dimitry Bertaud  1,00 mio. €
2       Belmin Dizdarevic      100 K €
3          Becir Omeragic  4,50 mio. €
4              Bamo Meïté  4,00 mio. €
5            Kiki Kouyaté  3,00 mio. €
6           Modibo Sagnan  3,00 mio. €
7     Christopher Jullien  1,00 mio. €
8            Yaël Mouanga      600 K €
9       Nikola Maksimović      300 K €
10           Craig Mamilo            -
11          Issiaga Sylla  1,50 mio. €
12       Lucas Mincarelli      900 K €
13       Théo Sainte-Luce      800 K €
14            Enzo Tchato  2,50 mio. €
15           Falaye Sacko  1,50 mio. €
16  Wilfried Ndollo Bille      200 K €
17          Joris Chotard  6,00 mio. €
18        Rabby Nzingoula  2,50 mio. €
19           Birama Touré    800 K €
20          Gabriel Barès    300 K €
21       Abdoulaye Camara            -
22           Khalil Fayad  3,00 mio. €
23           Jordan Ferri  2,00 mio. €
24          Stefan Dzodic      200 K €
25          Téji Savanier  2,50 mio. €
26           Nicolas Pays      700 K €
27          Théo Chennahi      150 K €
28             Simon Cara       50 K €
29           Wahbi Khazri  1,00 mio. €
30           Mousa Tamari  6,00 mio. €
31          Arnaud Nordin  5,00 mio. €
32       Tanguy Coulibaly  1,50 mio. €
33         Othmane Maamma      600 K €
34           Axel Guéguin      300 K €
35             Akor Adams  5,00 mio. €
36            Andy Delort  1,50 mio. €
37         Yanis Issoufou      200 K €
38          Junior Ndiaye      150 K €
39           Glenn Ngosso            -

In [ ]:
for link in Links :
    collect_player_data(link)

### Final dataframes from TM

In [ ]:
PlayersTM

,Player,Age,Nation,Value
0,Benjamin Lecomte,France,26 avr. 1991 (34),"1,50 mio. €"
1,Dimitry Bertaud,"RD Congo, France",6 juin 1998 (27),"1,00 mio. €"
2,Belmin Dizdarevic,Bosnie-Herzégovine,9 août 2001 (23),100 K €
3,Becir Omeragic,"Suisse, Bosnie-Herzégovine",20 janv. 2002 (23),"4,50 mio. €"
4,Bamo Meïté,"Côte d'Ivoire, France",3 déc. 2001 (23),"4,00 mio. €"
...,...,...,...,...
653,Martín Satriano,20 févr. 2001 (24),"Uruguay, Italie","5,00 mio. €"
654,Wesley Saïd,19 avr. 1995 (30),"France, Comores","3,00 mio. €"
655,Goduine Koyalipou,15 févr. 2000 (25),"République Centrafricaine, France","2,50 mio. €"
656,Florian Sotoca,25 oct. 1990 (34),France,"2,00 mio. €"
657,Rémy Labeau Lascary,3 mars 2003 (22),"Guadeloupe, France","2,00 mio. €"